---
- name: "Install packages for selenium server for Ubuntu/Debian"
  apt: name={{ item }} state=latest
  with_items:
      - openjdk-7-jdk
      - firefox
      - xvfb
      - fluxbox
      - x11-apps
      - x11vnc
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-scalable
      - xfonts-cyrillic
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Install packages for selenium server or CentOS/Red Hat"
  yum: name={{ item }} state=latest
  with_items:
      - java-1.7.0-openjdk
      - firefox
      - xorg-x11-server-Xvfb
      - x11vnc
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: before_install.yml

- name: Download Selenium server (Jar file)
  get_url:
    url: "{{ selenium_download_url }}"
    dest: "{{ selenium_server_path }}/{{ selenium_jar_file }}"
  environment: proxy_env
  sudo: yes

- name: Update owner
  file: path={{ selenium_server_path }}/{{ selenium_jar_file }} owner={{ selenium_user }} group={{ selenium_group }}
  sudo: yes

- name: Create symlink
  file: src={{ selenium_server_path }}/{{ selenium_jar_file }}  dest={{ selenium_server_path }}/{{ selenium_default_name }} state=link owner={{ selenium_user }} group={{ selenium_group }}

- include: supervisord.yml
