---
- include: before_install.yml

- name: "Install packages for selenium server for Ubuntu/Debian"
  apt: name={{ item }} state=latest
  with_items:
      - openjdk-7-jdk
      - xvfb
      - fluxbox
      - x11-apps
      - x11vnc
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-scalable
      - xfonts-cyrillic
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Install packages for selenium server or CentOS/Red Hat"
  yum: name={{ item }} state=latest
  with_items:
      - java-1.7.0-openjdk
      - xorg-x11-server-Xvfb
      - x11vnc
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Download Selenium server (Jar file)
  get_url:
    url: "{{ selenium_server.download_url }}"
    dest: "{{ selenium_server.server_path }}/{{ selenium_server.jar_file }}"
  environment: proxy_env
  sudo: yes

- name: Update owner
  file: path={{ selenium_server.server_path }}/{{ selenium_server.jar_file }} owner={{ selenium_server.user }} group={{ selenium_server.group }}
  sudo: yes

- include: fluxbox.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: supervisord.yml

- include: firewalld.yml

- include: firefox.yml
