---
- name: delete file nsnproxy.sh
  file: src=/etc/profile.d/nsnproxy.sh state=absent
  ignore_errors: True

- name: list yum.repos.d
  raw: find /etc/yum.repos.d/ -type f -name "*.repo"
  register: yum.repos

- name: remove proxy from yum.repos.d
  lineinfile: dest={{ item }} state=absent regexp="^%proxy"
  with_items: yum.repos.stdout_lines

- name: add proxy for internal hosts
  lineinfile:
    dest="/etc/environment"
    regexp="{{ item.name }}"
    line="{{ item.value }}"
  with_items:
    - { name: "^http_proxy", value: "http_proxy='{{ proxy_env.http_proxy }}'" }
    - { name: "^HTTP_PROXY", value: "HTTP_PROXY='{{ proxy_env.http_proxy }}'" }
    - { name: "^https_proxy", value: "https_proxy='{{ proxy_env.https_proxy }}'" }
    - { name: "^HTTPS_PROXY", value: "HTTPS_PROXY='{{ proxy_env.https_proxy }}'" }
    - { name: "^no_proxy", value: "no_proxy='{{ proxy_env.no_proxy }}'" }
    - { name: "^NO_PROXY", value: "NO_PROXY='{{ proxy_env.no_proxy }}'" }
