---

- name: Restart Selenium services
  shell: supervisorctl restart all

- name: reload supervisor
  service: name=supervisor state=reloaded

- name: reread supervisord config
  shell: supervisorctl reread

- name: add programs to process group
  shell: supervisorctl add {{item.name}}
  when: supervisor.programs is defined
  with_items: supervisor.programs

- name: change supervisord programs states
  shell: supervisorctl start {{item.name}}
  when: supervisor.programs is defined
  with_items: supervisor.programs
